version: "2"

linters:
  default: none
  enable:
    - containedctx
    - contextcheck
    - fatcontext
    - godot
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - usetesting
  disable:
    # Disable unparam as it flags functions with intentional error returns for interface consistency
    - unparam
    