name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'

    - name: Run all tests
      run: go test -v ./...

    - name: Run E2E tests
      run: go test -v -tags=e2e --local ./...

    - name: Run integration tests
      run: go test -v -tags=integration ./...
      env:
        CI: true
