name: Manual Verification Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  manual-verification:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Display Go version
        run: go version

      - name: Build tako binary
        run: go build -o ./tako ./cmd/tako

      - name: Build takotest binary
        run: go build -o ./takotest ./cmd/takotest

      - name: Configure Git for testing
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "GitHub Actions"

      - name: Make scripts executable
        run: chmod +x test/scripts/*.sh

      - name: Run all verification scripts
        run: |
          echo "Running all verification scripts in test/scripts/"
          for script in test/scripts/verify-*.sh; do
            if [ -f "$script" ]; then
              echo "=========================================="
              echo "Running: $(basename "$script")"
              echo "=========================================="
              "$script"
              echo "✅ $(basename "$script") completed successfully"
              echo ""
            fi
          done
          echo "🎉 All verification scripts passed!"

      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: manual-test-artifacts
          path: |
            test-*/
            /tmp/tako_*
          retention-days: 7